return {
	"williamboman/mason.nvim",
	opts = {
		ensure_installed = {
			"bash-debug-adapter",
			"bash-language-server",
			"debugpy",
			"dockerfile-language-server",
			"eslint-lsp",
			"hadolint",
			"jedi-language-server",
			"json-lsp",
			"jsonlint",
			"lua-language-server",
			"markdown-toc",
			"markdownlint-cli2",
			"marksman",
			"prettier",
			"pyright",
			"ruff",
			"shellcheck",
			"shfmt",
			-- "snyk-ls",
			"stylua",
			"taplo",
			"terraform-ls",
			"tflint",
			"yaml-language-server",
			"yamllint",
		},
	},
}
