lastupdatecheck: 0
recentrepos:
- /Users/mmorri929/.dotfiles
- /Users/mmorri929/Code/xerxes-config
- /Users/mmorri929/code/xerxes-auth
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
